// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("LogicalHacking.ScholarKpi")>]
[<assembly: AssemblyProductAttribute("LogicalHacking.ScholarKpi")>]
[<assembly: AssemblyDescriptionAttribute("A tool for analysing publication related key performance indicates (KPIs) based on the information available at the Google Scholar page of an author.")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "LogicalHacking.ScholarKpi"
    let [<Literal>] AssemblyProduct = "LogicalHacking.ScholarKpi"
    let [<Literal>] AssemblyDescription = "A tool for analysing publication related key performance indicates (KPIs) based on the information available at the Google Scholar page of an author."
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
