// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("LogicalHacking.ScholarKpiConsole")>]
[<assembly: AssemblyProductAttribute("LogicalHacking.ScholarKpi")>]
[<assembly: AssemblyDescriptionAttribute("A tool for analysing publication related key performance indicates (KPIs) based on the information available at the Google Scholar page of an author.")>]
[<assembly: AssemblyVersionAttribute("0.0.0")>]
[<assembly: AssemblyFileVersionAttribute("0.0.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "LogicalHacking.ScholarKpiConsole"
    let [<Literal>] AssemblyProduct = "LogicalHacking.ScholarKpi"
    let [<Literal>] AssemblyDescription = "A tool for analysing publication related key performance indicates (KPIs) based on the information available at the Google Scholar page of an author."
    let [<Literal>] AssemblyVersion = "0.0.0"
    let [<Literal>] AssemblyFileVersion = "0.0.0"
    let [<Literal>] AssemblyConfiguration = "Release"
